// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG0qt5tki9IOy5b82LKPnnkCUTTTHoJ5E',
    appId: '1:696693723600:android:c4705235ed2a23bc6b69d5',
    messagingSenderId: '696693723600',
    projectId: 'flutter-chat-7fe22',
    storageBucket: 'flutter-chat-7fe22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATxCZpiDQz6KdoY3BneDss43QcSdGxP_Y',
    appId: '1:696693723600:ios:48291be989e01cfd6b69d5',
    messagingSenderId: '696693723600',
    projectId: 'flutter-chat-7fe22',
    storageBucket: 'flutter-chat-7fe22.appspot.com',
    iosClientId: '696693723600-hfs311hjss7v6djbvom4ibdf0qkn51v1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATxCZpiDQz6KdoY3BneDss43QcSdGxP_Y',
    appId: '1:696693723600:ios:48291be989e01cfd6b69d5',
    messagingSenderId: '696693723600',
    projectId: 'flutter-chat-7fe22',
    storageBucket: 'flutter-chat-7fe22.appspot.com',
    iosClientId: '696693723600-hfs311hjss7v6djbvom4ibdf0qkn51v1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
